version: 2
jobs:
  trigger_blog_deploy:
    docker:
      - image: circleci/ruby:2.4.3-node-browsers
    steps:
      - checkout
      - run:
          name: Trigger Blog Deploy
          command: .circleci/trigger-blog-deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - trigger_blog_deploy:
          filters:
            branches:
              only: master